algoritmo "semnome"
// Função :
// Autor :
// Data : 17/10/2024
// Seção de Declarações 
var
c:inteiro
cadeira:vetor[1..10] de inteiro
inicio
      escreval("------------------------------------------------------------------------")
      para c<-1 ate 10 faca
      Escreva("  [B", cadeira[c], "]")
      FIMPARA
      escreval
      escreval("------------------------------------------------------------------------")

       fimalgoritmo
