algoritmo "WORKOUT"]

var
nome:caractere
idade:inteiro
sim_nao1:logico
inicio
escreval("Olá, tudo bem?, eu me chamo X, e você, como se chama? ")
escreva("Eu me chamo: ")
leia(nome)
escreva("Muito prazer, ", nome)
escreval(", agora me diga a sua idade, por favor")
escreva("A minha idade é: ")
leia(idade)
escreval("Muito bem,agora vou te fazer algumas perguntas, tudo bem por você? ")
leia(sim_nao1)
se falso entao escreva("adeus")
se verdadeiro entao escreva("que bom")
  CONTINUAR
fimalgoritmo
