algoritmo "contador"
// Função :
// Autor :
// Data : 27/08/2024
// Seção de Declarações 
var
n1, valor, salto:real
inicio
      n1<-0
      escreva("Quer contar até quanto?")
      leia(valor)
      escreva("Deseja que o salto seja de quanto?")
      leia(salto)
      enquanto (n1<=valor) faca
      escreval(n1)
      n1<-n1+salto

      fimenquanto
      escreva("terminei de contar em:", n1-salto)
fimalgoritmo
