algoritmo "contadorinteligente"

var
i, f:inteiro
inicio
      escreval("inicio:")
      leia(I)
      escreval("fim")
      leia(f)
      se(i<f)entao
                  escreval(i)
                  enquanto (i<f)faca
                  i<-i+1
                  escreval(i)
                  fimenquanto
      senao
           escreval(i)
           enquanto (i>f)faca
           i<-i-1
           escreval(i)
           fimenquanto
      fimse

fimalgoritmo
