algoritmo "semnome"
// Função :
// Autor :                                                                         // 0   1   1   2 3 5 8 13 21
// Data : 18/09/2024                                                               // p1  p2  ptf
// Seção de Declarações 
var
p1, p2,PTF, c:inteiro
inicio
p1<-0
p2<- 1
      escreva(p1, p2)
      para c<- 0 ate 10 faca
      ptf<-p1+p2
      escreva(ptf)
      p1<-p2
      p2<-ptf
      



      fimpara
      
fimalgoritmo
