algoritmo "semnome"
// Função :
// Autor :
// Data : 26/09/2024
// Seção de Declarações 
var
N1, N2, R:inteiro
funcao soma(X, Y:inteiro):inteiro
inicio                         //veja que como retornei uma soma, não precisei atribuir uma variavel de soma (S)
retorne X+Y
fimfuncao
inicio
N1<-5 //posso também mandar o usuário digitar 2 números
N2<-4
R<-soma(N1, N2)
escreva("A soma é", R)

fimalgoritmo
